In [ ]:
#variable
a=10
print("i am" ,a,"years old")


In [ ]:
#arthmetic ops on integer variables
a=int(input("enter a number: "))
b=int(input("enter b number: "))
print("addition is",a+b)
print("subtraction is",a-b)
print("multiplication is",a*b)
print("quotient is",a/b)
print("remainder is",a%b)
print("power is",a**b)
print("floor divison is",a//b)



enter a number: 50005


KeyboardInterrupt: Interrupted by user

In [ ]:
#problem statement
#take salary from user if the salary is more than 50,000 there is 10% tax print his final salary
s=int(input("enter salary"))
if(s>50000):
  tax=(10/100)*s
  s=s-tax
  print("final salary is",s)
else:
  print(" final salary is",s,"no tax")





enter salary3000
 final salary is 3000 no tax


In [ ]:
#get the salary from the user if salry is more than or equal to 50000 apply 10% tax reduction if the salary is less than 50000 apply 5% tax if the salary is more than 70000 apply 12% tax if salary exetes 1L print ur promoted to next level
s=int(input("enter salary"))
if(s<=50000):
  tax=(5/100)*s
  s=s-tax
  print("final salary is",s)
elif(s>50000 and s<=70000):
   tax=(10/100)*s
   s=s-tax
   print("final salary is",s)
elif(s>70000 and s<=100000):
   tax=(12/100)*s
   s=s-tax
   print("final salary is",s)
else:
  print("you are promoted")





enter salary70000
final salary is 63000.0


In [ ]:
#for
n=int(input("enter a number"))
for i in range(1,11):
  print(n,"*",i,"=",n*i)


enter a number10
10 * 1 = 10
10 * 2 = 20
10 * 3 = 30
10 * 4 = 40
10 * 5 = 50
10 * 6 = 60
10 * 7 = 70
10 * 8 = 80
10 * 9 = 90
10 * 10 = 100


In [ ]:
#while
n=int(input("enter a number"))
i=1
while(i<=10):
  print(n,"*",i,"=",n*i)
  i=i+1

enter a number5
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50


In [ ]:
#list
l=[1,"kill",'you',True]
for i in l:
  print(i)



1
kill
you
True


In [6]:
#sort
a=[5,4,3,2,1]
a.sort()
print(a)
b=sorted(a)
print(b)


[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


In [ ]:
#mutable
l.append("appended")
print(l)
l.insert(4,"hi")
print(l)

[1, 'kill', 'you', True, 'appended', 'appended']
[1, 'kill', 'you', True, 'hi', 'appended', 'appended']


In [ ]:
#extend
l2=["s",1]
l.extend(l2)
print(l)
print(l2)


[1, 'kill', 'you', True, 'hi', 'appended', 's', 1, 's', 1, 's', 1, 's', 's', 's', 1]
['s', 1]


In [ ]:
#pop with index
l.pop(3)
print(l)


[1, 'kill', 'you', 'hi', 'appended', 's', 1]


In [ ]:
#remove with element
l2=['s','r','i','y','a']
l2.remove('s')
print(l2)

['r', 'i', 'y', 'a']


In [ ]:
#problem statement
#create a list of 10 integers elements and print their squares and saves these squares in new lists
l=[1,2,3,4,5,6,7,8,9,10]
s=[]
for i in l:
  s.append(i**2)
print(s)


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
#list comprehension for
lc=[1,2,3,4,5,]
sc=[i*i for i in lc]
print(sc)



[1, 4, 9, 16, 25]


In [ ]:
#list comprehension if
r=[i*i for i in li if i>25]
print(r)

[900, 1225, 1600, 2025]


In [ ]:
#list comprehension else
#new list =[(st of if) if (cond) else (st of else) for]
l=[25,30,35,40,45,50,55,60,65]
res=[i**2 if i>50 else 'X' for i in l]
print(res)


['X', 'X', 'X', 'X', 'X', 'X', 3025, 3600, 4225]


In [ ]:
#take the salary from the user if the salary is less than 50k 10% tax otherwise 15% tax
s=int(input("enter salary"))
l=[print(s-(s*0.1)) if s<50000 else print(s-(s*0.15))]
l1=[78000,800000,800,2560,100]
li=[(s-(s*0.1)) if s<50000 else (s-(s*0.15)) for s in l1]
print(li)

enter salary50000
42500.0
[66300.0, 680000.0, 720.0, 2304.0, 90.0]


In [ ]:
#dictionary
dict1={1:'sri',2:'yash',3:'ram',4:'tri'}
print(dict1)

{1: 'sri', 2: 'yash', 3: 'ram', 4: 'tri'}


In [ ]:
#key & values
print(dict1.keys())
print(dict1.values())
print(dict1[1])



dict_keys([1, 2, 3, 4])
dict_values(['sri', 'yash', 'ram', 'tri'])
sri


In [ ]:
dict3={"dept":"CSE","detalis":{"year":2,"sec":"d","count":71}}
print(dict3["detalis"]["sec"])

d


In [ ]:
dict3={"dept":"CSE","details":{"year":2,"sec":"d","count":71}}
print("year is",dict3["details"]["year"])
print("sec is",dict3["details"]["sec"])
print("count is",dict3["details"]["count"])


year is 2
sec is d
count is 71


In [ ]:
idl=[1,2,3,4,5]
name=["sri","yash","ram","tri"]
new_dict=(zip(idl,name))
for i in new_dict:
  print(i)

(1, 'sri')
(2, 'yash')
(3, 'ram')
(4, 'tri')


In [ ]:
#NUMPY
import numpy as np
A=np.array([1,2,3,4]) #1d array
print(A.ndim)
print(A.shape)

1
(4,)


In [ ]:
import numpy as np
A=np.array([[1,2,3,4],[5,6,7,8]])#2d array
#elements in each row=column
print(A.ndim)
print(A.shape)
print(A)


2
(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
A=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(A.ndim)
print(A.shape)
print(A)

3
(2, 2, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [ ]:
A=np.ones((4,4))#g,r,c
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
A=np.eye(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
A=np.arange(1,10,2)#start,stop,step
print(A)
print(type(A))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
#print all the numbers that are divisble by 8 using arange function b/w 1and1000
A=np.arange(8,1000,8)
print(A)

[  8  16  24  32  40  48  56  64  72  80  88  96 104 112 120 128 136 144
 152 160 168 176 184 192 200 208 216 224 232 240 248 256 264 272 280 288
 296 304 312 320 328 336 344 352 360 368 376 384 392 400 408 416 424 432
 440 448 456 464 472 480 488 496 504 512 520 528 536 544 552 560 568 576
 584 592 600 608 616 624 632 640 648 656 664 672 680 688 696 704 712 720
 728 736 744 752 760 768 776 784 792 800 808 816 824 832 840 848 856 864
 872 880 888 896 904 912 920 928 936 944 952 960 968 976 984 992]


In [ ]:
#spliting arange into n numbers with common differences
import numpy as np
A=np.linspace(49,50,10)
print(A)

[49.         49.11111111 49.22222222 49.33333333 49.44444444 49.55555556
 49.66666667 49.77777778 49.88888889 50.        ]


In [ ]:
#sets
s={'s',1,'r',2,True}
print(s)
#len
print(len(s))
#type
print(type(s))
#update
s.update("i")
print(s)
#remove
s.remove('i')
print(s)
#pop
s.pop()
print(s)
#clear
s.clear()
print(s)



{1, 2, 's', 'r'}
4
<class 'set'>
{1, 2, 'r', 's', 'i'}
{1, 2, 'r', 's'}
{2, 'r', 's'}
set()


In [ ]:
#set operations
s1={1,2,3,4,5}
s2={4,5,6,7,8}
#union
print(s1.union(s2))
#intersection
print(s1.intersection(s2))
#difference
print(s1.difference(s2))
#symmetric_difference
print(s1.symmetric_difference(s2))
#subset
print(s1.issubset(s2))
#superset
print(s1.issuperset(s2))
#disjoint
print(s1.isdisjoint(s2))


{1, 2, 3, 4, 5, 6, 7, 8}
{4, 5}
{1, 2, 3}
{1, 2, 3, 6, 7, 8}
False
False
False


In [ ]:
#tuples
t=(1,2,3,4,5)
print(t)
#concat
t1=(1,2,3)+(4,5,6,3)
print(t1)
#lenght
print(len(t))
#repetition
t2=("hi! ")*4
print(t2)
#in
print(3 in t1)
#index
print(t[0])
print(t[0:4])
#updating tuple using list
tl=list(t)
tl[1]=55
t=tuple(tl)
print(t)
#type
print(type(t))
#count
print(t.count(5))
#index
print(t.index(5))

(1, 2, 3, 4, 5)
(1, 2, 3, 4, 5, 6, 3)
5
hi! hi! hi! hi! 
True
1
(1, 2, 3, 4)
(1, 55, 3, 4, 5)
<class 'tuple'>
1
4
