In [ ]:
import numpy as np
A=np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np
A=np.linspace(5,7,12).reshape(4,3)
print(A)

[[5.         5.18181818 5.36363636]
 [5.54545455 5.72727273 5.90909091]
 [6.09090909 6.27272727 6.45454545]
 [6.63636364 6.81818182 7.        ]]


In [ ]:
B=np.array([1,2,3,4,5,6,7,8]).reshape(2,2,2)#reshape=changes needs saving in another variable
print(B)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
B=np.array([1,2,3,4,5,6,7,8])
B.resize(2,2,2)#changes the shape of original array
print(B)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#array operations
A=np.array([34,56,78,90])#list will throw an error while arrays iterate themseleves
B=np.array([7,9,3,12])
C=A-B
print(A-B)
print(A+B)

[27 47 75 78]
[ 41  65  81 102]


In [ ]:
#min max
A=np.array([34,56,78,90])
print(A.max())#max and min accepts numeric datatypes int and float
print(A.min())

90
34


In [ ]:
#one on one multiplication
A=np.array([34,56,78,90]).reshape(2,2)
B=np.array([7,9,3,12]).reshape(2,2)
print(A)
print("_____________________")
print(B)
C=A*B#one on one multiplication
print("_____________________")
print(C)

[[34 56]
 [78 90]]
_____________________
[[ 7  9]
 [ 3 12]]
_____________________
[[ 238  504]
 [ 234 1080]]


In [ ]:
#matrix multiplication
A=np.array([34,56,78,90]).reshape(2,2)
B=np.array([7,9,3,12]).reshape(2,2)
print(A)
print("_____________________")
print(B)
C=A@B#matrix multiplication
print("_____________________")
print(C)

[[34 56]
 [78 90]]
_____________________
[[ 7  9]
 [ 3 12]]
_____________________
[[ 406  978]
 [ 816 1782]]


In [ ]:
#matrix multiplication
A=np.array([34,56,78,90]).reshape(2,2)
B=np.array([7,9,3,12]).reshape(2,2)
print(A)
print("_____________________")
print(B)
C=A.dot(B)#matrix multiplication
print("_____________________")
print(C)

[[34 56]
 [78 90]]
_____________________
[[ 7  9]
 [ 3 12]]
_____________________
[[ 406  978]
 [ 816 1782]]


In [ ]:
A=np.array([34,56,78,90]).reshape(2,2)
print(A)
print("_____________________")
print(A.max(axis=0))#axis=0 : column
print("_____________________")
print(A.max(axis=1))#axis=1 : row
print("_____________________")
print(A.min(axis=0))#axis=0 : column
print("_____________________")
print(A.min(axis=1))#axis=1 : row

[[34 56]
 [78 90]]
_____________________
[78 90]
_____________________
[56 90]
_____________________
[34 56]
_____________________
[34 78]


In [ ]:
A=np.array([34,56,78,90]).reshape(2,2)
B=np.array([7,9,3,12]).reshape(2,2)
print(A)
print("_____________________")
print(B)
print("after vertically stacking arrays!")
print(np.vstack((A,B)))
print("_____________________")
print(np.hstack((A,B)))
print("_____________________")
print(np.stack((A,B),axis=0))
print("_____________________")
print(np.stack((A,B),axis=1))

[[34 56]
 [78 90]]
_____________________
[[ 7  9]
 [ 3 12]]
after vertically stacking arrays!
[[34 56]
 [78 90]
 [ 7  9]
 [ 3 12]]
_____________________
[[34 56  7  9]
 [78 90  3 12]]
_____________________
[[[34 56]
  [78 90]]

 [[ 7  9]
  [ 3 12]]]
_____________________
[[[34 56]
  [ 7  9]]

 [[78 90]
  [ 3 12]]]


In [ ]:
A=np.arange(30).reshape(2,3,5)
print(A)
print("after dstack")
print(np.dstack(A))#no.of rows =no.of groups
#no.of col in every group = no.of rows in every group
[0 0],[1,1],............
#original 2,3,5
#dstack   3,5,2

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
after dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
#splitting arrays!
A=np.arange(18).reshape(6,3)
print(A)
print("after splitting")
print(np.vsplit(A,3))#based on rows vsplit happens(no.of rows should be divisble by that number)
print("_____________________")
print(np.hsplit(A,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]]), array([[12, 13, 14],
       [15, 16, 17]])]
_____________________
[array([[ 0],
       [ 3],
       [ 6],
       [ 9],
       [12],
       [15]]), array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]])]


In [ ]:
A=np.arange(18).reshape(6,3)
print(A)
print("after splitting")
print(np.vsplit(A,(2,3)))#splitting the array using indexes
print("_____________________")
print(np.hsplit(A,(2,3)))


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting
[array([[0, 1, 2],
       [3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])]
_____________________
[array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13],
       [15, 16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([], shape=(6, 0), dtype=int64)]


In [ ]:
A=np.arange(18).reshape(3,6)
print(A)
print(A.argmax())#it gives the index of the highest element

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
17


In [ ]:
A=np.arange(18).reshape(3,6)
print(A)
print(A.argmax(axis=0))
print(A.argmax(axis=1))
#axis=0           #axis=1
  #0 0 0 0           0 1 2 3
  #1 1 1 1           0 1 2 3
  #2 2 2 2           0 1 2 3

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[2 2 2 2 2 2]
[5 5 5]


In [ ]:
A=np.arange(18).reshape(3,6)
print(A)
print(A.argmin())

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
0


In [ ]:
A=np.arange(18).reshape(3,6)
print(A)
print(A.argmin(axis=0))
print(A.argmin(axis=1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[0 0 0 0 0 0]
[0 0 0]


**STATISTICS**

In [ ]:
#MEAN,MEDIAN,STD,VAR
A=np.array([12,34,25,66,71,88])
print("MEAN :",np.mean(A))
print("MEDIAN :",np.median(A))
print("VARIANCE:",np.var(A))
print("STANDARD DEV :",np.std(A))

MEAN : 49.333333333333336
MEDIAN : 50.0
VARIANCE: 743.888888888889
STANDARD DEV : 27.274326552435515


**TRIGONOMETRY**

In [ ]:
A=np.pi
print(A)#radians

3.141592653589793


In [ ]:
np.rad2deg(A)

180.0

In [ ]:
B=np.array([np.pi/4,np.pi/3,np.pi/2,np.pi/1])
print(B)

[0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
print(np.rad2deg(B))

[ 45.  60.  90. 180.]


In [ ]:
C=np.array([0,30,45,60,90,120,180])
D=np.deg2rad(C)
print(D)

[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]


In [ ]:
np.sin(C)


array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666,
        0.58061118, -0.80115264])

In [ ]:
np.cos(C)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362,
        0.81418097, -0.59846007])

In [ ]:
np.tan(C)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041,
        0.71312301,  1.33869021])

In [ ]:
np.arcsin(1)#sin^-1

1.5707963267948966

In [ ]:
np.arccos(1)#cos^-1

0.0

In [ ]:
np.arctan(1)#tan^-1

0.7853981633974483

In [ ]:
a=8
b=6
print(np.hypot(a,b))#hypotneuse

10.0


**SEARCHING!**

In [ ]:
A=np.array([90,3,45,21,34,90,21])
print(np.where(A==21))

(array([3, 6]),)


In [ ]:
A=np.array([90,3,45,21,34,90,21])
print(np.where(A%2==0))#even

(array([0, 4, 5]),)


In [ ]:
A=np.array([90,3,45,21,34,90,21])
print(np.where(A>25))#greater than 25

(array([0, 2, 4, 5]),)


In [ ]:
import numpy as np
A=np.array([1,2,3,4,5])
print(np.searchsorted(A,4))#3,21,34,45,90

3


**LINEAR ALGEBRA AND UFUNC**

In [ ]:
A=np.array([6,24,60,48,46])
B=np.array([3,1,5,9,4])
print(np.add(A,B))
print(np.subtract(A,B))

[ 9 25 65 57 50]
[ 3 23 55 39 42]


In [ ]:
print(np.divide(A,B))#quoitent
print(np.mod(A,B))#remiander
print(np.divmod(A,B))#both quo and rem



[1.66666667 4.         0.6        0.22222222 0.25      ]
[2 0 3 2 1]
(array([1, 4, 0, 0, 0]), array([2, 0, 3, 2, 1]))


In [ ]:
A=np.array([5,4,3,2,1])
print(np.sort(A))#sort
print(np.diff(A))#difference

[1 2 3 4 5]
[-1 -1 -1 -1]


**SET FUNCTIONS**

In [ ]:
A=np.array([1,2,3,4,5])
B=np.array([4,5,6,7,8,])
print(np.union1d(A,B))

[1 2 3 4 5 6 7 8]


In [ ]:
A=np.array([1,2,3,4,5])
B=np.array([4,5,6,7,8,])
print(np.setdiff1d(A,B))

[1 2 3]


In [ ]:
A=np.array([1,2,3,4,5])
B=np.array([4,5,6,7,8,])
print(np.intersect1d(A,B))

[4 5]


**ROUNDING**

In [ ]:
#trunc
A=np.trunc([-3.1666,3.6667])
print(A)

[-3.  3.]


In [ ]:
#fix
A=np.fix([-3.1666,3.6667])
print(A)

[-3.  3.]


In [ ]:
#around
A=np.around(3.1666,4)
print(A)

3.1666


In [ ]:
#floor
A=np.floor([-3.1666,3.6667])
print(A)

[-4.  3.]


In [ ]:
#ceil
A=np.ceil([-3.1666,3.1])
print(A)

[-3.  4.]


MORE FUNCTIONS

In [ ]:
A=np.array([3,4,16,19,10])
print(np.cumsum(A))

[ 3  7 23 42 52]


In [ ]:
A=np.array([3,4,16,19,10])
print(np.cumprod(A))

[    3    12   192  3648 36480]


In [ ]:
print(np.lcm(34,56))
print(np.gcd(445,655))

952
5


In [ ]:
A=np.array([45,65,30])
print(np.lcm.reduce(A))


1170


In [ ]:
A=np.array([45,65,30])
print(np.gcd.reduce(A))

5


In [ ]:
A=np.array([[1,2],[3,4]])
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


**RANDOM**

In [ ]:
from numpy import random as rd

In [ ]:
A=rd.rand()#n #default limit 0 to 0.99
print(A)

0.03092639565243005


In [ ]:
A=rd.rand(10)#default limit 0 to 0.99
print(A)

[0.13232488 0.92818259 0.30778598 0.6836049  0.76561987 0.39958861
 0.72519065 0.12358338 0.23942973 0.63355423]


In [ ]:
A=rd.randint(4)#randint(limit)==limit 0,1,2,3,4
print(A)

1


In [ ]:
A=rd.randint(50,size=6)#limit,size
print(A)

[11  8 36 11 18 40]


In [ ]:
A=rd.randint(50,size=(2,3))#limit,size
print(A)

[[48 15  5]
 [26 11  9]]


**JOINS!**

In [ ]:
A=np.array([1,2,3])
B=np.array([4,5,6])
#1x4 + 2x5 +3x6
print(np.inner(A,B))

32


In [ ]:
A=np.array([1,2,3])
B=np.array([4,5,6])
#1x4 , 1x5 ,1x6 : 2x4 , 2x5 ,2x6 : 3x4, 3x5 ,3x6
print(np.outer(A,B))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
A=np.array([1,2,3])
B=np.array([4,5,6])
#det
print(np.cross(A,B))

[-3  6 -3]
